sudo: required
dist: trusty

language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2/repository

script:
  - mvn test

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn jacoco:report coveralls:report

before_deploy:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

deploy:
  - provider: script
    script: ./travis/publish.sh
    on:
      branch: master
